<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SnapBoard.Infrastructure\SnapBoard.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\SnapBoard.Application\SnapBoard.Application.csproj" />
    <ProjectReference Include="..\..\src\SnapBoard.Domain\SnapBoard.Domain.csproj" />
  </ItemGroup>

</Project>
