<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishTrimmed Condition="'$(PublishAot)' == 'true'">true</PublishTrimmed>
    <TrimMode Condition="'$(PublishAot)' == 'true'">full</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SnapBoard.Platform.Abstractions\SnapBoard.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\SnapBoard.Platform.MacOS\SnapBoard.Platform.MacOS.csproj" />
  </ItemGroup>
</Project>
